# Update
name: DO NOT RUN THIS

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    #- name: Install dependencies
    #  run: |
    #    python -m pip install --upgrade pip
    #    pip install pynput
    - name: Run The File
      run: |
        python /home/runner/work/Projects/Projects/break/breaker.py
        git commit -m "Made smallest text file larger"
    #- name: Save the Text File
    #  run: |
    #    git commit -m "Made smallest text file larger"
